import { Module2TagType, TagFieldConfig, TagFieldId, TagLayoutPreset } from '../../types';

export const AVAILABLE_FONTS = [
  { id: 'Arial', name: 'Arial (Sans-serif)' },
  { id: 'Helvetica', name: 'Helvetica (Clean)' },
  { id: 'Times New Roman', name: 'Times New Roman (Serif)' },
  { id: 'Courier New', name: 'Courier New (Monospace)' },
  { id: 'Verdana', name: 'Verdana (Legible)' },
  { id: 'Georgia', name: 'Georgia (Serif)' },
  { id: 'Impact', name: 'Impact (Heavy Promo)' },
  { id: 'Trebuchet MS', name: 'Trebuchet MS' },
];

export interface TagFieldMeta {
  id: TagFieldId;
  label: string;
  category: 'text' | 'price' | 'barcode' | 'badge' | 'media';
  description: string;
}

export const ALL_TAG_FIELDS: TagFieldMeta[] = [
  { id: 'description', label: 'DESCRIPTION', category: 'text', description: 'Product title / trade description' },
  { id: 'sku', label: 'SKU / CODE', category: 'text', description: 'Stock keeping unit / product code' },
  { id: 'barcode', label: 'BARCODE', category: 'barcode', description: 'Scannable barcode & number' },
  { id: 'regularPrice', label: 'REGULAR PRICE', category: 'price', description: 'Retail price / WAS original price' },
  { id: 'promoPrice', label: 'PRICE PROMO', category: 'price', description: 'Special offer promotional price point' },
  { id: 'priceUnit', label: 'PRICE UNIT', category: 'price', description: 'Per piece, pack, or unit measurement' },
  { id: 'locator', label: 'LOCATOR', category: 'badge', description: 'Shelf aisle / bin location coordinate' },
  { id: 'promoHeader', label: 'PROMO HEADER', category: 'text', description: 'Top promotional banner bar (PP Tag)' },
  { id: 'logo', label: 'STORE LOGO', category: 'media', description: 'Prince store brand emblem' },
  { id: 'buyPerAndUp', label: 'BUY PER AND UP', category: 'text', description: 'Custom promo tier text (e.g. BUY 3 PR1 AND UP)' },
  { id: 'tagDate', label: 'DATE', category: 'text', description: 'Tag date (e.g. 2/08/26)' },
];

/**
 * EXACT 7 Data Fields permitted for Yellow Tag:
 * 1. UPC
 * 2. DESCRIPTION
 * 3. BUY
 * 4. QTY
 * 5. UOM
 * 6. PRICE
 * 7. PER
 */
export const YELLOW_TAG_FIELD_METAS: TagFieldMeta[] = [
  { id: 'upc', label: 'UPC', category: 'text', description: 'UPC number (bold digits, no barcode lines)' },
  { id: 'description', label: 'DESCRIPTION', category: 'text', description: 'Product description / item name' },
  { id: 'buy', label: 'BUY', category: 'text', description: 'BUY condition prefix (default: BUY)' },
  { id: 'qty', label: 'QTY', category: 'text', description: 'Promo quantity number (from Excel QTY)' },
  { id: 'uom', label: 'UOM', category: 'text', description: 'Unit of measure (default: PCS AND UP)' },
  { id: 'price', label: 'PRICE', category: 'price', description: 'Selling price (always 2 decimal places)' },
  { id: 'per', label: 'PER', category: 'price', description: 'Price unit indicator (default: /PC)' },
];

/**
 * EXACT 6 Fields for White Tag:
 * 1. UPC / BARCODE
 * 2. DESCRIPTION
 * 3. PRICE
 * 4. SKU
 * 5. DATE
 * 6. LOGO
 */
export const WHITE_TAG_FIELD_METAS: TagFieldMeta[] = [
  { id: 'barcode', label: 'UPC / BARCODE', category: 'barcode', description: 'Scannable barcode lines + human-readable UPC' },
  { id: 'description', label: 'DESCRIPTION', category: 'text', description: 'Product description / trade name' },
  { id: 'price', label: 'PRICE', category: 'price', description: 'Selling price (always 2 decimal places)' },
  { id: 'sku', label: 'SKU', category: 'text', description: 'Stock keeping unit / code' },
  { id: 'date', label: 'DATE', category: 'text', description: 'Tag reference date (today if blank)' },
  { id: 'logo', label: 'LOGO', category: 'media', description: 'Store logo (Prince Retail)' },
];

export const LAYOUT2_YELLOW_FIELDS: TagFieldMeta[] = YELLOW_TAG_FIELD_METAS;
export const LAYOUT2_WHITE_FIELDS: TagFieldMeta[] = WHITE_TAG_FIELD_METAS;

export function createDefaultYellowTagFields(tagWidthMm: number = 60, tagHeightMm: number = 42): Record<TagFieldId, TagFieldConfig> {
  const w = tagWidthMm;
  const h = tagHeightMm;

  return {
    description: {
      id: 'description',
      name: 'DESCRIPTION',
      visible: true,
      x: 3.5,
      y: 3.0,
      width: Math.round(w * 0.56),
      height: 11,
      fontFamily: 'Arial',
      fontSizePt: 9.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'top',
      textTransform: 'uppercase',
      textWrap: true,
      maxLines: 2,
      lineHeightPt: 11,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    upc: {
      id: 'upc',
      name: 'UPC',
      visible: true,
      x: Math.round(w * 0.58),
      y: 3.0,
      width: w - Math.round(w * 0.58) - 3.5,
      height: 7,
      fontFamily: 'Arial',
      fontSizePt: 9.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    buy: {
      id: 'buy',
      name: 'BUY',
      visible: true,
      x: 3.5,
      y: 16.5,
      width: 14,
      height: 8,
      fontFamily: 'Arial',
      fontSizePt: 12.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    qty: {
      id: 'qty',
      name: 'QTY',
      visible: true,
      x: 18,
      y: 16.5,
      width: 14,
      height: 8,
      fontFamily: 'Arial',
      fontSizePt: 13.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    uom: {
      id: 'uom',
      name: 'UOM',
      visible: true,
      x: 3.5,
      y: 24.5,
      width: 32,
      height: 6.5,
      fontFamily: 'Arial',
      fontSizePt: 8.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    price: {
      id: 'price',
      name: 'PRICE',
      visible: true,
      x: Math.round(w * 0.44),
      y: 18.0,
      width: Math.round(w * 0.38),
      height: 14,
      fontFamily: 'Arial',
      fontSizePt: 24,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      currencySymbol: '₱',
      showCurrencySymbol: true,
      decimalPlaces: 2,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    per: {
      id: 'per',
      name: 'PER',
      visible: true,
      x: w - 14,
      y: 23.5,
      width: 10.5,
      height: 6.5,
      fontFamily: 'Arial',
      fontSizePt: 8.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    // Backwards compatibility mappings
    regularPrice: {
      id: 'regularPrice',
      name: 'Price',
      visible: true,
      x: Math.round(w * 0.44),
      y: 18.0,
      width: Math.round(w * 0.38),
      height: 14,
      fontFamily: 'Arial',
      fontSizePt: 24,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      currencySymbol: '₱',
      showCurrencySymbol: true,
      decimalPlaces: 2,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    promoPrice: { id: 'promoPrice', name: 'Promo Price', visible: false, x: 0, y: 0, width: 0, height: 0, fontFamily: 'Arial', fontSizePt: 12, fontWeight: 'normal', fontStyle: 'normal', textDecoration: 'none', textColor: '#000000', textAlign: 'left', verticalAlign: 'top', textTransform: 'none', textWrap: false, maxLines: 1, borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0 },
    priceUnit: {
      id: 'priceUnit',
      name: 'Unit',
      visible: true,
      x: w - 14,
      y: 23.5,
      width: 10.5,
      height: 6.5,
      fontFamily: 'Arial',
      fontSizePt: 8.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    sku: { id: 'sku', name: 'SKU', visible: false, x: 0, y: 0, width: 0, height: 0, fontFamily: 'Arial', fontSizePt: 8, fontWeight: 'normal', fontStyle: 'normal', textDecoration: 'none', textColor: '#000000', textAlign: 'left', verticalAlign: 'top', textTransform: 'none', textWrap: false, maxLines: 1, borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0 },
    barcode: {
      id: 'barcode',
      name: 'UPC',
      visible: true,
      x: Math.round(w * 0.58),
      y: 3.0,
      width: w - Math.round(w * 0.58) - 3.5,
      height: 7,
      fontFamily: 'Arial',
      fontSizePt: 9.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      showBarcodeLines: false,
    },
    locator: { id: 'locator', name: 'Locator', visible: false, x: 0, y: 0, width: 0, height: 0, fontFamily: 'Arial', fontSizePt: 8, fontWeight: 'normal', fontStyle: 'normal', textDecoration: 'none', textColor: '#000000', textAlign: 'left', verticalAlign: 'top', textTransform: 'none', textWrap: false, maxLines: 1, borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0 },
    promoHeader: { id: 'promoHeader', name: 'Promo Header', visible: false, x: 0, y: 0, width: 0, height: 0, fontFamily: 'Arial', fontSizePt: 8, fontWeight: 'normal', fontStyle: 'normal', textDecoration: 'none', textColor: '#000000', textAlign: 'left', verticalAlign: 'top', textTransform: 'none', textWrap: false, maxLines: 1, borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0 },
    logo: { id: 'logo', name: 'Logo', visible: false, x: 0, y: 0, width: 0, height: 0, fontFamily: 'Arial', fontSizePt: 8, fontWeight: 'normal', fontStyle: 'normal', textDecoration: 'none', textColor: '#000000', textAlign: 'left', verticalAlign: 'top', textTransform: 'none', textWrap: false, maxLines: 1, borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0 },
    buyPerAndUp: {
      id: 'buyPerAndUp',
      name: 'BUY',
      visible: true,
      x: 3.5,
      y: 16.5,
      width: 28,
      height: 14,
      fontFamily: 'Arial',
      fontSizePt: 12.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 2,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    tagDate: { id: 'tagDate', name: 'Date', visible: false, x: 0, y: 0, width: 0, height: 0, fontFamily: 'Arial', fontSizePt: 8, fontWeight: 'normal', fontStyle: 'normal', textDecoration: 'none', textColor: '#000000', textAlign: 'left', verticalAlign: 'top', textTransform: 'none', textWrap: false, maxLines: 1, borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0 },
    date: { id: 'date', name: 'Date', visible: false, x: 0, y: 0, width: 0, height: 0, fontFamily: 'Arial', fontSizePt: 8, fontWeight: 'normal', fontStyle: 'normal', textDecoration: 'none', textColor: '#000000', textAlign: 'left', verticalAlign: 'top', textTransform: 'none', textWrap: false, maxLines: 1, borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0 },
  };
}

export function createDefaultWhiteTagFields(tagWidthMm: number = 60, tagHeightMm: number = 42): Record<TagFieldId, TagFieldConfig> {
  const w = tagWidthMm;
  const h = tagHeightMm;

  return {
    description: {
      id: 'description',
      name: 'DESCRIPTION',
      visible: true,
      x: 3.0,
      y: 2.5,
      width: Math.round(w * 0.62),
      height: 9.5,
      fontFamily: 'Arial',
      fontSizePt: 8.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'top',
      textTransform: 'uppercase',
      textWrap: true,
      maxLines: 2,
      lineHeightPt: 10,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    date: {
      id: 'date',
      name: 'DATE',
      visible: true,
      x: w - 23,
      y: 2.5,
      width: 20,
      height: 4.5,
      fontFamily: 'Arial',
      fontSizePt: 7.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'center',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    tagDate: {
      id: 'tagDate',
      name: 'DATE',
      visible: true,
      x: w - 23,
      y: 2.5,
      width: 20,
      height: 4.5,
      fontFamily: 'Arial',
      fontSizePt: 7.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'center',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    price: {
      id: 'price',
      name: 'PRICE',
      visible: true,
      x: Math.round(w * 0.40),
      y: 7.5,
      width: Math.round(w * 0.57),
      height: 12,
      fontFamily: 'Arial',
      fontSizePt: 22,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      currencySymbol: '₱',
      showCurrencySymbol: true,
      decimalPlaces: 2,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    regularPrice: {
      id: 'regularPrice',
      name: 'PRICE',
      visible: true,
      x: Math.round(w * 0.40),
      y: 7.5,
      width: Math.round(w * 0.57),
      height: 12,
      fontFamily: 'Arial',
      fontSizePt: 22,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      currencySymbol: '₱',
      showCurrencySymbol: true,
      decimalPlaces: 2,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    logo: {
      id: 'logo',
      name: 'LOGO',
      visible: true,
      x: 3.0,
      y: 13.0,
      width: 16,
      height: 6.5,
      fontFamily: 'Arial',
      fontSizePt: 8,
      fontWeight: 'normal',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    barcode: {
      id: 'barcode',
      name: 'UPC / BARCODE',
      visible: true,
      x: 21.0,
      y: 19.5,
      width: Math.round(w * 0.49),
      height: 11,
      fontFamily: 'Arial',
      fontSizePt: 6.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'center',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      barcodeFormat: 'CODE128',
      showBarcodeLines: true,
      showBarcodeText: true,
      barcodeTextSizePt: 6.5,
      barcodeAlign: 'center',
    },
    sku: {
      id: 'sku',
      name: 'SKU',
      visible: true,
      x: 3.0,
      y: 21.0,
      width: 17,
      height: 6.5,
      fontFamily: 'Courier New',
      fontSizePt: 8,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    // Backwards compatibility mappings
    promoPrice: { id: 'promoPrice', name: 'Promo Price', visible: false, x: 0, y: 0, width: 0, height: 0, fontFamily: 'Arial', fontSizePt: 12, fontWeight: 'normal', fontStyle: 'normal', textDecoration: 'none', textColor: '#000000', textAlign: 'left', verticalAlign: 'top', textTransform: 'none', textWrap: false, maxLines: 1, borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0 },
    priceUnit: { id: 'priceUnit', name: 'Price Unit', visible: false, x: 0, y: 0, width: 0, height: 0, fontFamily: 'Arial', fontSizePt: 8, fontWeight: 'normal', fontStyle: 'normal', textDecoration: 'none', textColor: '#000000', textAlign: 'left', verticalAlign: 'top', textTransform: 'none', textWrap: false, maxLines: 1, borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0 },
    locator: { id: 'locator', name: 'Locator', visible: false, x: 0, y: 0, width: 0, height: 0, fontFamily: 'Arial', fontSizePt: 8, fontWeight: 'normal', fontStyle: 'normal', textDecoration: 'none', textColor: '#000000', textAlign: 'left', verticalAlign: 'top', textTransform: 'none', textWrap: false, maxLines: 1, borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0 },
    promoHeader: { id: 'promoHeader', name: 'Promo Header', visible: false, x: 0, y: 0, width: 0, height: 0, fontFamily: 'Arial', fontSizePt: 8, fontWeight: 'normal', fontStyle: 'normal', textDecoration: 'none', textColor: '#000000', textAlign: 'left', verticalAlign: 'top', textTransform: 'none', textWrap: false, maxLines: 1, borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0 },
    buyPerAndUp: { id: 'buyPerAndUp', name: 'Buy Per', visible: false, x: 0, y: 0, width: 0, height: 0, fontFamily: 'Arial', fontSizePt: 8, fontWeight: 'normal', fontStyle: 'normal', textDecoration: 'none', textColor: '#000000', textAlign: 'left', verticalAlign: 'top', textTransform: 'none', textWrap: false, maxLines: 1, borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0 },
    upc: { id: 'upc', name: 'UPC', visible: false, x: 0, y: 0, width: 0, height: 0, fontFamily: 'Arial', fontSizePt: 8, fontWeight: 'normal', fontStyle: 'normal', textDecoration: 'none', textColor: '#000000', textAlign: 'left', verticalAlign: 'top', textTransform: 'none', textWrap: false, maxLines: 1, borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0 },
    buy: { id: 'buy', name: 'BUY', visible: false, x: 0, y: 0, width: 0, height: 0, fontFamily: 'Arial', fontSizePt: 8, fontWeight: 'normal', fontStyle: 'normal', textDecoration: 'none', textColor: '#000000', textAlign: 'left', verticalAlign: 'top', textTransform: 'none', textWrap: false, maxLines: 1, borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0 },
    qty: { id: 'qty', name: 'QTY', visible: false, x: 0, y: 0, width: 0, height: 0, fontFamily: 'Arial', fontSizePt: 8, fontWeight: 'normal', fontStyle: 'normal', textDecoration: 'none', textColor: '#000000', textAlign: 'left', verticalAlign: 'top', textTransform: 'none', textWrap: false, maxLines: 1, borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0 },
    uom: { id: 'uom', name: 'UOM', visible: false, x: 0, y: 0, width: 0, height: 0, fontFamily: 'Arial', fontSizePt: 8, fontWeight: 'normal', fontStyle: 'normal', textDecoration: 'none', textColor: '#000000', textAlign: 'left', verticalAlign: 'top', textTransform: 'none', textWrap: false, maxLines: 1, borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0 },
    per: { id: 'per', name: 'PER', visible: false, x: 0, y: 0, width: 0, height: 0, fontFamily: 'Arial', fontSizePt: 8, fontWeight: 'normal', fontStyle: 'normal', textDecoration: 'none', textColor: '#000000', textAlign: 'left', verticalAlign: 'top', textTransform: 'none', textWrap: false, maxLines: 1, borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0 },
  };
}

export function createDefaultFieldsForShelftag(tagWidthMm: number, tagHeightMm: number): Record<string, TagFieldConfig> {
  const w = tagWidthMm;
  const h = tagHeightMm;
  const isCompact = w < 60;
  const isWide = w >= 90;

  return {
    description: {
      id: 'description',
      name: 'DESCRIPTION',
      visible: true,
      x: isWide ? 4 : 3,
      y: isCompact ? 6 : 8.5,
      width: isWide ? w - 8 : w - 6,
      height: isCompact ? 9 : 11.5,
      fontFamily: 'Arial',
      fontSizePt: isCompact ? 7.5 : isWide ? 11 : 9.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'top',
      textTransform: 'uppercase',
      textWrap: true,
      maxLines: 2,
      lineHeightPt: 11,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    sku: {
      id: 'sku',
      name: 'SKU / CODE',
      visible: true,
      x: isWide ? 4 : 3,
      y: isCompact ? 1.5 : 2.5,
      width: isWide ? 36 : 28,
      height: isCompact ? 3.8 : 4.5,
      fontFamily: 'Arial',
      fontSizePt: isCompact ? 6.5 : 7.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      prefixText: 'SKU: ',
    },
    locator: {
      id: 'locator',
      name: 'LOCATOR',
      visible: true,
      x: isWide ? 42 : 32,
      y: isCompact ? 1.5 : 2.5,
      width: isWide ? 22 : 16,
      height: isCompact ? 3.8 : 4.5,
      fontFamily: 'Courier New',
      fontSizePt: isCompact ? 6.5 : 7,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'center',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'solid',
      borderWidthPx: 1,
      borderRadiusMm: 0.5,
      borderColor: '#000000',
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0.5,
      paddingRightMm: 0.5,
      locatorBadge: true,
    },
    barcode: {
      id: 'barcode',
      name: 'BARCODE',
      visible: true,
      x: isWide ? 4 : 3,
      y: isCompact ? 16 : 21,
      width: isWide ? 45 : Math.min(36, w * 0.52),
      height: isCompact ? 11 : 14.5,
      fontFamily: 'Courier New',
      fontSizePt: 6.5,
      fontWeight: 'normal',
      fontStyle: 'normal',
      textDecoration: 'none',
      textAlign: 'left',
      verticalAlign: 'bottom',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      barcodeFormat: 'CODE128',
      showBarcodeText: true,
      barcodeTextSizePt: 6.5,
      barcodeAlign: 'left',
    },
    regularPrice: {
      id: 'regularPrice',
      name: 'REGULAR PRICE',
      visible: true,
      x: isWide ? 52 : Math.max(34, w * 0.52),
      y: isCompact ? 16 : 21,
      width: isWide ? w - 56 : w - Math.max(34, w * 0.52) - 3,
      height: isCompact ? 9 : 12,
      fontFamily: 'Arial',
      fontSizePt: isCompact ? 11 : isWide ? 18 : 14.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'right',
      verticalAlign: 'bottom',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      currencySymbol: '₱',
      showCurrencySymbol: true,
      decimalPlaces: 2,
      prefixText: 'RETAIL PRICE',
    },
    promoPrice: {
      id: 'promoPrice',
      name: 'PRICE PROMO',
      visible: false, // White tag is regular
      x: isWide ? 52 : Math.max(34, w * 0.52),
      y: isCompact ? 16 : 21,
      width: isWide ? w - 56 : w - Math.max(34, w * 0.52) - 3,
      height: isCompact ? 9 : 11,
      fontFamily: 'Arial',
      fontSizePt: 13,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#E31B23',
      textAlign: 'right',
      verticalAlign: 'bottom',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      currencySymbol: '₱',
      showCurrencySymbol: true,
      decimalPlaces: 2,
    },
    priceUnit: {
      id: 'priceUnit',
      name: 'PRICE UNIT',
      visible: true,
      x: isWide ? 52 : Math.max(34, w * 0.52),
      y: isCompact ? 26 : h - 7,
      width: isWide ? w - 56 : w - Math.max(34, w * 0.52) - 3,
      height: 4.5,
      fontFamily: 'Arial',
      fontSizePt: isCompact ? 6 : 7,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    promoHeader: {
      id: 'promoHeader',
      name: 'PROMO HEADER',
      visible: false,
      x: 0,
      y: 0,
      width: w,
      height: 6,
      fontFamily: 'Arial',
      fontSizePt: 8,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#ffffff',
      textAlign: 'left',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      backgroundColor: '#E31B23',
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 2,
      paddingRightMm: 2,
    },
    logo: {
      id: 'logo',
      name: 'STORE LOGO',
      visible: true,
      x: w - 16,
      y: isCompact ? 1.5 : 2.5,
      width: 13,
      height: isCompact ? 3.8 : 4.5,
      fontFamily: 'Arial',
      fontSizePt: 8,
      fontWeight: 'normal',
      fontStyle: 'normal',
      textDecoration: 'none',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    buyPerAndUp: {
      id: 'buyPerAndUp',
      name: 'BUY PER AND UP',
      visible: false,
      x: 3,
      y: 13,
      width: 30,
      height: 8,
      fontFamily: 'Arial',
      fontSizePt: 9,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: true,
      maxLines: 2,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    tagDate: {
      id: 'tagDate',
      name: 'DATE',
      visible: false,
      x: w - 24,
      y: 2.5,
      width: 21,
      height: 5,
      fontFamily: 'Arial',
      fontSizePt: 7.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
  };
}

export function createDefaultFieldsForPPTag(tagWidthMm: number, tagHeightMm: number): Record<string, TagFieldConfig> {
  const w = tagWidthMm;
  const h = tagHeightMm;
  const isLarge = w >= 80;
  const bannerH = Math.max(6.5, Math.round(h * 0.17));

  return {
    promoHeader: {
      id: 'promoHeader',
      name: 'PROMO HEADER',
      visible: true,
      x: 0,
      y: 0,
      width: w,
      height: bannerH,
      fontFamily: 'Arial',
      fontSizePt: isLarge ? 9.5 : 8,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#ffffff',
      textAlign: 'left',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      backgroundColor: '#E31B23',
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 2.5,
      paddingRightMm: 2.5,
    },
    sku: {
      id: 'sku',
      name: 'SKU / CODE',
      visible: true,
      x: 3,
      y: bannerH + 1.5,
      width: isLarge ? 34 : 26,
      height: 4.5,
      fontFamily: 'Arial',
      fontSizePt: isLarge ? 8.5 : 7.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      prefixText: 'SKU: ',
    },
    locator: {
      id: 'locator',
      name: 'LOCATOR',
      visible: true,
      x: isLarge ? 40 : 31,
      y: bannerH + 1.5,
      width: isLarge ? 20 : 15,
      height: 4.5,
      fontFamily: 'Courier New',
      fontSizePt: isLarge ? 8 : 7,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#ffffff',
      textAlign: 'center',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0.5,
      backgroundColor: '#000000',
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0.5,
      paddingRightMm: 0.5,
      locatorBadge: true,
    },
    logo: {
      id: 'logo',
      name: 'STORE LOGO',
      visible: true,
      x: w - 16,
      y: bannerH + 1.5,
      width: 13,
      height: 4.5,
      fontFamily: 'Arial',
      fontSizePt: 8,
      fontWeight: 'normal',
      fontStyle: 'normal',
      textDecoration: 'none',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    description: {
      id: 'description',
      name: 'DESCRIPTION',
      visible: true,
      x: 3,
      y: bannerH + 7,
      width: w - 6,
      height: isLarge ? 14 : 11,
      fontFamily: 'Arial',
      fontSizePt: isLarge ? 12 : 9.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'top',
      textTransform: 'uppercase',
      textWrap: true,
      maxLines: 2,
      lineHeightPt: 11,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    barcode: {
      id: 'barcode',
      name: 'BARCODE',
      visible: true,
      x: 3,
      y: isLarge ? h - 22 : h - 17,
      width: isLarge ? 46 : Math.min(35, w * 0.52),
      height: isLarge ? 18 : 13.5,
      fontFamily: 'Courier New',
      fontSizePt: 6.5,
      fontWeight: 'normal',
      fontStyle: 'normal',
      textDecoration: 'none',
      textAlign: 'left',
      verticalAlign: 'bottom',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      barcodeFormat: 'CODE128',
      showBarcodeText: true,
      barcodeTextSizePt: 6.5,
      barcodeAlign: 'left',
    },
    regularPrice: {
      id: 'regularPrice',
      name: 'REGULAR PRICE',
      visible: true,
      x: isLarge ? 52 : Math.max(34, w * 0.52),
      y: isLarge ? h - 21 : h - 16.5,
      width: isLarge ? w - 55 : w - Math.max(34, w * 0.52) - 3,
      height: 4.5,
      fontFamily: 'Arial',
      fontSizePt: isLarge ? 9 : 7.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#E31B23',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      currencySymbol: '₱',
      showCurrencySymbol: true,
      decimalPlaces: 2,
      strikeThrough: true,
      prefixText: 'WAS ',
    },
    promoPrice: {
      id: 'promoPrice',
      name: 'PRICE PROMO',
      visible: true,
      x: isLarge ? 52 : Math.max(34, w * 0.52),
      y: isLarge ? h - 16.5 : h - 12,
      width: isLarge ? w - 55 : w - Math.max(34, w * 0.52) - 3,
      height: isLarge ? 11 : 8.5,
      fontFamily: 'Arial',
      fontSizePt: isLarge ? 19 : 14.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#E31B23',
      textAlign: 'right',
      verticalAlign: 'bottom',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      currencySymbol: '₱',
      showCurrencySymbol: true,
      decimalPlaces: 2,
    },
    priceUnit: {
      id: 'priceUnit',
      name: 'PRICE UNIT',
      visible: true,
      x: isLarge ? 52 : Math.max(34, w * 0.52),
      y: h - 5.5,
      width: isLarge ? w - 55 : w - Math.max(34, w * 0.52) - 3,
      height: 4,
      fontFamily: 'Arial',
      fontSizePt: isLarge ? 7.5 : 6.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    buyPerAndUp: {
      id: 'buyPerAndUp',
      name: 'BUY PER AND UP',
      visible: false,
      x: 3,
      y: 13,
      width: 30,
      height: 8,
      fontFamily: 'Arial',
      fontSizePt: 9,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: true,
      maxLines: 2,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    tagDate: {
      id: 'tagDate',
      name: 'DATE',
      visible: false,
      x: w - 24,
      y: 2.5,
      width: 21,
      height: 5,
      fontFamily: 'Arial',
      fontSizePt: 7.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
  };
}

/**
 * Creates Field Configs for Layout Option 2 — Reference White ShelfTag
 * Only displays: Description, Date, Price, Prince Logo, Barcode, SKU
 */
export function createLayout2FieldsForShelftag(tagWidthMm: number, tagHeightMm: number): Record<string, TagFieldConfig> {
  const w = tagWidthMm;

  return {
    description: {
      id: 'description',
      name: 'DESCRIPTION',
      visible: true,
      x: 3,
      y: 2.5,
      width: Math.round(w * 0.62),
      height: 10,
      fontFamily: 'Arial',
      fontSizePt: 8.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'top',
      textTransform: 'uppercase',
      textWrap: true,
      maxLines: 2,
      lineHeightPt: 10.5,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    tagDate: {
      id: 'tagDate',
      name: 'DATE',
      visible: true,
      x: w - 24,
      y: 2.5,
      width: 21,
      height: 5,
      fontFamily: 'Arial',
      fontSizePt: 8,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'right',
      verticalAlign: 'top',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    regularPrice: {
      id: 'regularPrice',
      name: 'PRICE',
      visible: true,
      x: Math.round(w * 0.44),
      y: 8,
      width: Math.round(w * 0.53),
      height: 13,
      fontFamily: 'Arial',
      fontSizePt: 22,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      decimalPlaces: 2,
    },
    logo: {
      id: 'logo',
      name: 'LOGO',
      visible: true,
      x: w - 16,
      y: 7.5,
      width: 13,
      height: 4.5,
      fontFamily: 'Arial',
      fontSizePt: 8,
      fontWeight: 'normal',
      fontStyle: 'normal',
      textDecoration: 'none',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    barcode: {
      id: 'barcode',
      name: 'BARCODE',
      visible: true,
      x: Math.round(w * 0.45),
      y: 21.5,
      width: Math.round(w * 0.52),
      height: 16.5,
      fontFamily: 'Arial',
      fontSizePt: 6.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'center',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      barcodeFormat: 'CODE128',
      showBarcodeText: true,
      barcodeTextSizePt: 6.5,
      barcodeAlign: 'center',
    },
    sku: {
      id: 'sku',
      name: 'SKU / CODE',
      visible: true,
      x: 3,
      y: 27,
      width: Math.round(w * 0.42),
      height: 8,
      fontFamily: 'Courier New',
      fontSizePt: 7.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    promoPrice: {
      id: 'promoPrice',
      name: 'PRICE PROMO',
      visible: false,
      x: 0, y: 0, width: 0, height: 0,
      fontFamily: 'Arial', fontSizePt: 10, fontWeight: 'bold', fontStyle: 'normal', textDecoration: 'none',
      textColor: '#000000', textAlign: 'left', verticalAlign: 'middle', textTransform: 'none', textWrap: false, maxLines: 1,
      borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0,
    },
    locator: {
      id: 'locator',
      name: 'LOCATOR',
      visible: false,
      x: 0, y: 0, width: 0, height: 0,
      fontFamily: 'Arial', fontSizePt: 7, fontWeight: 'bold', fontStyle: 'normal', textDecoration: 'none',
      textColor: '#000000', textAlign: 'left', verticalAlign: 'middle', textTransform: 'none', textWrap: false, maxLines: 1,
      borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0,
    },
    promoHeader: {
      id: 'promoHeader',
      name: 'PROMO HEADER',
      visible: false,
      x: 0, y: 0, width: 0, height: 0,
      fontFamily: 'Arial', fontSizePt: 8, fontWeight: 'bold', fontStyle: 'normal', textDecoration: 'none',
      textColor: '#000000', textAlign: 'left', verticalAlign: 'middle', textTransform: 'none', textWrap: false, maxLines: 1,
      borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0,
    },
    priceUnit: {
      id: 'priceUnit',
      name: 'PRICE UNIT',
      visible: false,
      x: 0, y: 0, width: 0, height: 0,
      fontFamily: 'Arial', fontSizePt: 7, fontWeight: 'bold', fontStyle: 'normal', textDecoration: 'none',
      textColor: '#000000', textAlign: 'left', verticalAlign: 'middle', textTransform: 'none', textWrap: false, maxLines: 1,
      borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0,
    },
    buyPerAndUp: {
      id: 'buyPerAndUp',
      name: 'BUY PER AND UP',
      visible: false,
      x: 0, y: 0, width: 0, height: 0,
      fontFamily: 'Arial', fontSizePt: 8, fontWeight: 'bold', fontStyle: 'normal', textDecoration: 'none',
      textColor: '#000000', textAlign: 'left', verticalAlign: 'middle', textTransform: 'none', textWrap: false, maxLines: 1,
      borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0,
    },
  };
}

/**
 * Creates Field Configs for Layout Option 2 — Reference Yellow PP Tag
 * Only displays: Description, Barcode, Buy Per and Up, Price, Unit
 */
export function createLayout2FieldsForPPTag(tagWidthMm: number, tagHeightMm: number): Record<string, TagFieldConfig> {
  const w = tagWidthMm;

  return {
    description: {
      id: 'description',
      name: 'Description',
      visible: true,
      x: 3.5,
      y: 3.0,
      width: Math.round(w * 0.55),
      height: 10.5,
      fontFamily: 'Arial',
      fontSizePt: 8.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'top',
      textTransform: 'uppercase',
      textWrap: true,
      maxLines: 2,
      lineHeightPt: 10.5,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    barcode: {
      id: 'barcode',
      name: 'Barcode',
      visible: true,
      x: w - 28,
      y: 2.5,
      width: 25,
      height: 6,
      fontFamily: 'Courier New',
      fontSizePt: 8,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      barcodeFormat: 'CODE128',
      showBarcodeLines: false,
      showBarcodeText: true,
      barcodeTextSizePt: 8,
      barcodeAlign: 'right',
    },
    buyPerAndUp: {
      id: 'buyPerAndUp',
      name: 'BUY PER AND UP',
      visible: true,
      x: 3.5,
      y: 15.0,
      width: Math.round(w * 0.38),
      height: 15.5,
      fontFamily: 'Arial',
      fontSizePt: 9.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: true,
      maxLines: 2,
      lineHeightPt: 11,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    regularPrice: {
      id: 'regularPrice',
      name: 'Price',
      visible: true,
      x: Math.round(w * 0.41),
      y: 14.5,
      width: Math.round(w * 0.42),
      height: 15.5,
      fontFamily: 'Arial',
      fontSizePt: 22,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      showCurrencySymbol: true,
      currencySymbol: '₱',
      decimalPlaces: 2,
    },
    priceUnit: {
      id: 'priceUnit',
      name: 'Unit',
      visible: true,
      x: Math.round(w * 0.84),
      y: 20.0,
      width: Math.round(w * 0.14),
      height: 8.5,
      fontFamily: 'Arial',
      fontSizePt: 9.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      prefixText: '/ ',
    },
    sku: {
      id: 'sku',
      name: 'SKU / CODE',
      visible: false,
      x: 0, y: 0, width: 0, height: 0,
      fontFamily: 'Arial', fontSizePt: 7, fontWeight: 'bold', fontStyle: 'normal', textDecoration: 'none',
      textColor: '#000000', textAlign: 'left', verticalAlign: 'middle', textTransform: 'none', textWrap: false, maxLines: 1,
      borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0,
    },
    locator: {
      id: 'locator',
      name: 'LOCATOR',
      visible: false,
      x: 0, y: 0, width: 0, height: 0,
      fontFamily: 'Arial', fontSizePt: 7, fontWeight: 'bold', fontStyle: 'normal', textDecoration: 'none',
      textColor: '#000000', textAlign: 'left', verticalAlign: 'middle', textTransform: 'none', textWrap: false, maxLines: 1,
      borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0,
    },
    promoHeader: {
      id: 'promoHeader',
      name: 'PROMO HEADER',
      visible: false,
      x: 0, y: 0, width: 0, height: 0,
      fontFamily: 'Arial', fontSizePt: 8, fontWeight: 'bold', fontStyle: 'normal', textDecoration: 'none',
      textColor: '#000000', textAlign: 'left', verticalAlign: 'middle', textTransform: 'none', textWrap: false, maxLines: 1,
      borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0,
    },
    promoPrice: {
      id: 'promoPrice',
      name: 'PRICE PROMO',
      visible: false,
      x: 0, y: 0, width: 0, height: 0,
      fontFamily: 'Arial', fontSizePt: 10, fontWeight: 'bold', fontStyle: 'normal', textDecoration: 'none',
      textColor: '#000000', textAlign: 'left', verticalAlign: 'middle', textTransform: 'none', textWrap: false, maxLines: 1,
      borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0,
    },
    logo: {
      id: 'logo',
      name: 'STORE LOGO',
      visible: false,
      x: 0, y: 0, width: 0, height: 0,
      fontFamily: 'Arial', fontSizePt: 8, fontWeight: 'bold', fontStyle: 'normal', textDecoration: 'none',
      textColor: '#000000', textAlign: 'left', verticalAlign: 'middle', textTransform: 'none', textWrap: false, maxLines: 1,
      borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0,
    },
    tagDate: {
      id: 'tagDate',
      name: 'DATE',
      visible: false,
      x: 0, y: 0, width: 0, height: 0,
      fontFamily: 'Arial', fontSizePt: 7, fontWeight: 'bold', fontStyle: 'normal', textDecoration: 'none',
      textColor: '#000000', textAlign: 'left', verticalAlign: 'middle', textTransform: 'none', textWrap: false, maxLines: 1,
      borderStyle: 'none', borderWidthPx: 0, borderRadiusMm: 0, paddingTopMm: 0, paddingBottomMm: 0, paddingLeftMm: 0, paddingRightMm: 0,
    },
  };
}

// Built-in Presets for ShelfTag (White)
export const DEFAULT_SHELFTAG_PRESETS: TagLayoutPreset[] = [
  {
    id: 'shelftag-std-65x42',
    name: 'Standard Shelf Edge (3-Col)',
    tagType: 'shelftag',
    description: '65 × 42 mm • 3 Cols × 6 Rows (18 tags/A4) - Perfect 3-column retail shelf channel',
    isBuiltIn: true,
    tagWidthMm: 65,
    tagHeightMm: 42,
    paperSize: 'A4',
    orientation: 'portrait',
    columns: 3,
    rowGapMm: 3,
    colGapMm: 2.5,
    topMarginMm: 8,
    sideMarginMm: 5,
    yellowPalette: 'golden',
    currencySymbol: '₱',
    showBorder: true,
    showCutGuides: true,
    showLogo: true,
    fields: createDefaultFieldsForShelftag(65, 42),
  },
  {
    id: 'shelftag-compact-54x32',
    name: 'Compact Strip Tag',
    tagType: 'shelftag',
    description: '54 × 32 mm • 3 Cols × 8 Rows (24 tags/A4) - High density for tight cosmetic shelves',
    isBuiltIn: true,
    tagWidthMm: 54,
    tagHeightMm: 32,
    paperSize: 'A4',
    orientation: 'portrait',
    columns: 3,
    rowGapMm: 2.5,
    colGapMm: 3,
    topMarginMm: 8,
    sideMarginMm: 6,
    yellowPalette: 'golden',
    currencySymbol: '₱',
    showBorder: true,
    showCutGuides: true,
    showLogo: true,
    fields: createDefaultFieldsForShelftag(54, 32),
  },
  {
    id: 'shelftag-wide-100x50',
    name: 'Standard Wide ShelfTag',
    tagType: 'shelftag',
    description: '100 × 50 mm • 2 Cols × 5 Rows (10 tags/A4) - Generous wide format with big text',
    isBuiltIn: true,
    tagWidthMm: 100,
    tagHeightMm: 50,
    paperSize: 'A4',
    orientation: 'portrait',
    columns: 2,
    rowGapMm: 4,
    colGapMm: 5,
    topMarginMm: 10,
    sideMarginMm: 5,
    yellowPalette: 'golden',
    currencySymbol: '₱',
    showBorder: true,
    showCutGuides: true,
    showLogo: true,
    fields: createDefaultFieldsForShelftag(100, 50),
  },
];

// Built-in Presets for PP Tag (Yellow / Promo)
export const DEFAULT_PPTAG_PRESETS: TagLayoutPreset[] = [
  {
    id: 'pptag-std-65x42',
    name: 'Standard PP Promo Tag (3-Col)',
    tagType: 'pp_tag',
    description: '65 × 42 mm • 3 Cols × 6 Rows (18 tags/A4) - Perfect 3-column high-visibility yellow promo',
    isBuiltIn: true,
    tagWidthMm: 65,
    tagHeightMm: 42,
    paperSize: 'A4',
    orientation: 'portrait',
    columns: 3,
    rowGapMm: 3,
    colGapMm: 2.5,
    topMarginMm: 8,
    sideMarginMm: 5,
    yellowPalette: 'golden',
    currencySymbol: '₱',
    showBorder: true,
    showCutGuides: true,
    showLogo: true,
    promoHeader: 'SPECIAL BUY',
    fields: createDefaultFieldsForPPTag(65, 42),
  },
  {
    id: 'pptag-feature-82x52',
    name: 'Medium Feature / Price Point',
    tagType: 'pp_tag',
    description: '82 × 52 mm • 2 Cols × 5 Rows (10 tags/A4) - Eye-catching mid-aisle & gondola end-caps',
    isBuiltIn: true,
    tagWidthMm: 82,
    tagHeightMm: 52,
    paperSize: 'A4',
    orientation: 'portrait',
    columns: 2,
    rowGapMm: 4,
    colGapMm: 4,
    topMarginMm: 8,
    sideMarginMm: 8,
    yellowPalette: 'golden',
    currencySymbol: '₱',
    showBorder: true,
    showCutGuides: true,
    showLogo: true,
    promoHeader: 'PROMO TAG',
    fields: createDefaultFieldsForPPTag(82, 52),
  },
  {
    id: 'pptag-talker-96x66',
    name: 'Large Talker / PP Tag',
    tagType: 'pp_tag',
    description: '96 × 66 mm • 2 Cols × 4 Rows (8 tags/A4) - Giant promotional standout for pallet bins',
    isBuiltIn: true,
    tagWidthMm: 96,
    tagHeightMm: 66,
    paperSize: 'A4',
    orientation: 'portrait',
    columns: 2,
    rowGapMm: 5,
    colGapMm: 5,
    topMarginMm: 8,
    sideMarginMm: 8,
    yellowPalette: 'golden',
    currencySymbol: '₱',
    showBorder: true,
    showCutGuides: true,
    showLogo: true,
    promoHeader: 'SUPER SAVINGS',
    fields: createDefaultFieldsForPPTag(96, 66),
  },
];

// Built-in Presets for Layout Option 2 (Reference Layout)
export const DEFAULT_LAYOUT2_SHELFTAG_PRESETS: TagLayoutPreset[] = [
  {
    id: 'shelftag-ref-std-65x42',
    name: 'Standard Reference ShelfTag (3-Col)',
    tagType: 'shelftag',
    description: '65 × 42 mm • Reference layout with Description, Date, Price, Logo, Barcode, SKU',
    isBuiltIn: true,
    layoutOption: 2,
    tagWidthMm: 65,
    tagHeightMm: 42,
    paperSize: 'A4',
    orientation: 'portrait',
    columns: 3,
    rowGapMm: 3,
    colGapMm: 2.5,
    topMarginMm: 8,
    sideMarginMm: 5,
    yellowPalette: 'golden',
    currencySymbol: '₱',
    showBorder: true,
    showCutGuides: true,
    showLogo: true,
    fields: createLayout2FieldsForShelftag(65, 42),
  },
  {
    id: 'shelftag-ref-compact-54x32',
    name: 'Compact Reference ShelfTag (3-Col)',
    tagType: 'shelftag',
    description: '54 × 32 mm • Compact reference tag for tighter shelf rails',
    isBuiltIn: true,
    layoutOption: 2,
    tagWidthMm: 54,
    tagHeightMm: 32,
    paperSize: 'A4',
    orientation: 'portrait',
    columns: 3,
    rowGapMm: 2.5,
    colGapMm: 3,
    topMarginMm: 8,
    sideMarginMm: 6,
    yellowPalette: 'golden',
    currencySymbol: '₱',
    showBorder: true,
    showCutGuides: true,
    showLogo: true,
    fields: createLayout2FieldsForShelftag(54, 32),
  },
  {
    id: 'shelftag-ref-med-82x52',
    name: 'Medium Reference ShelfTag (2-Col)',
    tagType: 'shelftag',
    description: '82 × 52 mm • 2-Col Reference shelf tag with prominent price',
    isBuiltIn: true,
    layoutOption: 2,
    tagWidthMm: 82,
    tagHeightMm: 52,
    paperSize: 'A4',
    orientation: 'portrait',
    columns: 2,
    rowGapMm: 4,
    colGapMm: 4,
    topMarginMm: 8,
    sideMarginMm: 8,
    yellowPalette: 'golden',
    currencySymbol: '₱',
    showBorder: true,
    showCutGuides: true,
    showLogo: true,
    fields: createLayout2FieldsForShelftag(82, 52),
  },
];

export const DEFAULT_LAYOUT2_PPTAG_PRESETS: TagLayoutPreset[] = [
  {
    id: 'pptag-ref-std-65x42',
    name: 'Standard Reference PP Tag (3-Col)',
    tagType: 'pp_tag',
    description: '65 × 42 mm • Reference Yellow layout: Description, Barcode, Buy Per & Up, Price, Unit',
    isBuiltIn: true,
    layoutOption: 2,
    tagWidthMm: 65,
    tagHeightMm: 42,
    paperSize: 'A4',
    orientation: 'portrait',
    columns: 3,
    rowGapMm: 3,
    colGapMm: 2.5,
    topMarginMm: 8,
    sideMarginMm: 5,
    yellowPalette: 'golden',
    currencySymbol: '₱',
    showBorder: true,
    showCutGuides: true,
    showLogo: false,
    fields: createLayout2FieldsForPPTag(65, 42),
  },
  {
    id: 'pptag-ref-compact-54x32',
    name: 'Compact Reference PP Tag (3-Col)',
    tagType: 'pp_tag',
    description: '54 × 32 mm • Compact Reference Yellow tag for high density rails',
    isBuiltIn: true,
    layoutOption: 2,
    tagWidthMm: 54,
    tagHeightMm: 32,
    paperSize: 'A4',
    orientation: 'portrait',
    columns: 3,
    rowGapMm: 2.5,
    colGapMm: 3,
    topMarginMm: 8,
    sideMarginMm: 6,
    yellowPalette: 'golden',
    currencySymbol: '₱',
    showBorder: true,
    showCutGuides: true,
    showLogo: false,
    fields: createLayout2FieldsForPPTag(54, 32),
  },
  {
    id: 'pptag-ref-med-82x52',
    name: 'Medium Reference PP Tag (2-Col)',
    tagType: 'pp_tag',
    description: '82 × 52 mm • 2-Col Reference Yellow promo tag with bold tier pricing',
    isBuiltIn: true,
    layoutOption: 2,
    tagWidthMm: 82,
    tagHeightMm: 52,
    paperSize: 'A4',
    orientation: 'portrait',
    columns: 2,
    rowGapMm: 4,
    colGapMm: 4,
    topMarginMm: 8,
    sideMarginMm: 8,
    yellowPalette: 'golden',
    currencySymbol: '₱',
    showBorder: true,
    showCutGuides: true,
    showLogo: false,
    fields: createLayout2FieldsForPPTag(82, 52),
  },
  {
    id: 'pptag-ref-talker-96x66',
    name: 'Large Reference Talker PP Tag (2-Col)',
    tagType: 'pp_tag',
    description: '96 × 66 mm • 2-Col Large Reference Yellow tag for bins & displays',
    isBuiltIn: true,
    layoutOption: 2,
    tagWidthMm: 96,
    tagHeightMm: 66,
    paperSize: 'A4',
    orientation: 'portrait',
    columns: 2,
    rowGapMm: 5,
    colGapMm: 5,
    topMarginMm: 8,
    sideMarginMm: 8,
    yellowPalette: 'golden',
    currencySymbol: '₱',
    showBorder: true,
    showCutGuides: true,
    showLogo: false,
    fields: createLayout2FieldsForPPTag(96, 66),
  },
];

// Local Storage Keys
export const STORAGE_SHELFTAG_PRESETS_KEY = 'prg_shelftag_presets_v2_2';
export const STORAGE_PPTAG_PRESETS_KEY = 'prg_pptag_presets_v2_2';
export const STORAGE_ACTIVE_SHELFTAG_ID_KEY = 'prg_active_shelftag_preset_id_v2_2';
export const STORAGE_ACTIVE_PPTAG_ID_KEY = 'prg_active_pptag_preset_id_v2_2';

export function loadPresetsFromStorage(tagType: Module2TagType, fallback?: TagLayoutPreset[]): TagLayoutPreset[] {
  const key = tagType === 'shelftag' ? STORAGE_SHELFTAG_PRESETS_KEY : STORAGE_PPTAG_PRESETS_KEY;
  const defaults = fallback || (tagType === 'shelftag' ? DEFAULT_SHELFTAG_PRESETS : DEFAULT_PPTAG_PRESETS);

  try {
    const raw = localStorage.getItem(key);
    if (!raw) return defaults;
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed) && parsed.length > 0) {
      return defaults.map(def => {
        const found = parsed.find((p: any) => p.id === def.id);
        if (!found) return def;
        if (def.isBuiltIn) {
          return {
            ...def,
            ...found,
            fields: {
              ...def.fields,
              ...found.fields,
            },
          };
        }
        return found;
      }).concat(parsed.filter((p: any) => !defaults.some(d => d.id === p.id)));
    }
  } catch (e) {
    console.warn('Failed to parse presets from storage', e);
  }
  return defaults;
}

export function savePresetsToStorage(tagType: Module2TagType, presets: TagLayoutPreset[]): void {
  const key = tagType === 'shelftag' ? STORAGE_SHELFTAG_PRESETS_KEY : STORAGE_PPTAG_PRESETS_KEY;
  try {
    localStorage.setItem(key, JSON.stringify(presets));
  } catch (e) {
    console.warn('Failed to save presets to storage', e);
  }
}

export function saveActivePreset(tagType: Module2TagType, presetId: string): void {
  const key = tagType === 'shelftag' ? STORAGE_ACTIVE_SHELFTAG_ID_KEY : STORAGE_ACTIVE_PPTAG_ID_KEY;
  try {
    localStorage.setItem(key, presetId);
  } catch (e) {
    console.warn('Failed to save active preset id', e);
  }
}

export function loadActivePresetId(tagType: Module2TagType): string | null {
  const key = tagType === 'shelftag' ? STORAGE_ACTIVE_SHELFTAG_ID_KEY : STORAGE_ACTIVE_PPTAG_ID_KEY;
  try {
    return localStorage.getItem(key);
  } catch {
    return null;
  }
}

export const DEFAULT_YELLOW_TAG_PRESET: TagLayoutPreset = {
  id: 'yellow_standard_preset',
  name: 'Standard Yellow PP Tag (3 × 5 — Letter)',
  description: 'Standard 60 × 42 mm physical layout: UPC, Description, BUY, QTY, UOM, Price, and PER',
  tagType: 'pp_tag',
  tagWidthMm: 60,
  tagHeightMm: 42,
  paperSize: 'LETTER',
  orientation: 'portrait',
  columns: 3,
  rowGapMm: 3,
  colGapMm: 3,
  topMarginMm: 8,
  sideMarginMm: 5,
  yellowPalette: 'golden',
  currencySymbol: '₱',
  showBorder: true,
  showCutGuides: true,
  showLogo: false,
  fields: createDefaultYellowTagFields(60, 42),
  isBuiltIn: true,
};

export const DEFAULT_WHITE_TAG_PRESET: TagLayoutPreset = {
  id: 'white_standard_preset',
  name: 'Standard White ShelfTag (3 × 5 — Letter)',
  description: 'Standard 60 × 42 mm physical layout: Description, Date, Price, Logo, Barcode, and SKU',
  tagType: 'shelftag',
  tagWidthMm: 60,
  tagHeightMm: 42,
  paperSize: 'LETTER',
  orientation: 'portrait',
  columns: 3,
  rowGapMm: 3,
  colGapMm: 3,
  topMarginMm: 8,
  sideMarginMm: 5,
  yellowPalette: 'golden',
  currencySymbol: '₱',
  showBorder: true,
  showCutGuides: true,
  showLogo: true,
  fields: createDefaultWhiteTagFields(60, 42),
  isBuiltIn: true,
};

